# Generated by Django 3.2.7 on 2021-09-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=500)),
                ('short_url_code', models.CharField(max_length=50)),
            ],
        ),
    ]
